### ISSUE TITLE
Document how to tune storage specs 

### ISSUE THREAD

**Issue by arajkumar** [VictoriaMetrics/prometheus-benchmark#11]
Currently there is no preferred approach to tune storage configuration for benchmark environment. Documenting the same would help the user to play with difference storage types(gp2, gp3, io,.. etc), IOPS and throughput.

**Comment by hagen1778** [comment]
Hello! The general recommendations are the same as here https://docs.victoriametrics.com/Troubleshooting.html#slow-data-ingestion
Even when VIctoriaMetrics is optimized for running on slow disks, using SSDs will just make performance better.

IOPS and throughput are vary only for clouds and each has its own specifications. A general recommendation is to have bigger disks because most of the cloud providers correlate IOPS allowance with disk size.
